name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        application:
          - cart
          - admin
          - landing-page
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Restore cached npm dependencies
        uses: actions/cache/restore@v3
        with:
          path: |
            node_modules
            ~/.cache/Cypress # needed for the Cypress binary
          key: npm-dependencies-${{ hashFiles('pnpm-lock.yaml') }}
      - run: pnpm install --frozen-lockfile
      - name: Cache npm dependencies
        uses: actions/cache/save@v3
        with:
          path: |
            node_modules
            ~/.cache/Cypress # needed for the Cypress binary
          key: npm-dependencies-${{ hashFiles('pnpm-lock.yaml') }}
      - run: pnpm nx test ${{ matrix.application }}
      - run: ls
      - uses: actions/upload-artifact@master
        with:
          name: ${{ matrix.application }}/dist
          path: ./dist
      
  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    strategy:
          matrix:
            option: ${{ needs.build-test.outputs.* }}
            env: [staging, production]
    environment:
      name: matrix.env
    steps:
      - uses: actions/checkout@main
      - name: debug
        run: echo '${{ toJSON(needs.build-test.outputs) }}'
      - uses: actions/download-artifact@master
        with:
          name: ${{ matrix.application }}/dist
          path: ./dist
      - run: ls
      - run: echo Deploying to $ENVIRONMENT